### ISSUE TITLE
Set up Hub API

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#1]
API to accept DMP metadata as JSON (see Sam’s [demo](https://www.rd-alliance.org/rda-output-adoption-webinar-series-data-management-plans)) 
`POST /data_management_plans/:id`
API to accept PDF file for a specific DMP DOI (to be versioned and preserved in repo in step 6) 
`PUT /data_management_plans/:id`
API that returns list of DMP DOIs for a given date range 
`GET /data_management_plans`
API that returns a DMP as JSON (following the [common standard model](https://github.com/RDA-DMP-Common/RDA-DMP-Common-Standard/blob/master/docs/index.md))
`GET /data_management_plans/:id`

**Comment by briri** [comment]
Going to close this one. The initial code this is in place. 

Still more work to be done but will open new more specific tickets.
