### ISSUE TITLE
Define security settings for landing pages

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmphub#10]
Allow Org admins to define what portions of the landing page are visible publicly. The admin should be able to define this at the Org or Department levels. For example:

- Do not display user contributor email addresses
- Do not display the abstract if funding has not been 'granted'

We will need to begin passing along a department in the RDA Common Standard JSON. Need to decide whose departmental affiliation to use ... e.g. use the Principal Investigator's first and the Data Contact (creator/author of the DMP) if no PI is available

**Comment by mariapraetzellis** [comment]
Holding off on doing this so closing.
