### ISSUE TITLE
Enable SSO from DMPTool users

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmphub#11]
Our initial users will be admins from the DMPTool, so allow DMPTool users to use SSO to sign-in. Their affiliation should be used to indicate what DOIs they have access to.

See related https://github.com/CDLUC3/dmptool/issues/190

**Comment by briri** [comment]
We will also need to ensure that the User's Org's ROR id, their ORCID, available departments and any DOI minting config are passed through as well (e.g. specific DOI shoulder). 

Should we also carry the Google Tracker through as well so they can have insight into stats for these landing pages?

**Comment by mariapraetzellis** [comment]
We're holding off on doing this so closing issue for now.
