### ISSUE TITLE
 REFINE ENVIRONMENT

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#111]
Continue testing the new system. Review the CloudFormation template and testing framework. 
Ensure we can nuke the entire AWS stack and rebuild from scratch including preservation of the DynamoDB content, S3 bucket contents and the Cognito user pool contents.

**Comment by briri** [comment]
closing this one. the individual tasks need to be done but not in the immediate future they also do not lend themselves to inclusion in an epic
