### ISSUE TITLE
Add versioning information to the DMP-ID landing page

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#126]
AWS has automated versioning information that is stored for each DMP. We can take the timestamped version links and add this information to the DMP-ID landing page. 

We will need to determine where on the page these links should be displayed. One idea is to include this as a timestamped listing of versions on the right-hand side of the page. Perhaps just under the current full-text narrative link. We will probably want to work with UX to best format the page and can time this work with #125.

**Comment by briri** [comment]
closing since this is already deployed to DMPHub production
