### ISSUE TITLE
Build Hub landing page 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#2]
Build out basic DMP landing page (uses [API](https://github.com/CDLUC3/dmphub/issues/1) : `GET /data_management_plans/:id`)

**Comment by mariapraetzellis** [comment]
All Common Standard fields will display on the Hub when they have values

Also add: Last updated date & Date created. 

Ability download PDF, JSON

**Comment by briri** [comment]
Going to close this one. The initial code this is in place.
