### ISSUE TITLE
DMPHub edits

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#20]
From our conversation on the initial DMPHub build. 

- [x] Add column for funder 
- [x] Make column sortable by updated date 
- [x] Make sections default to open automatically when you are looking at an individual DOI
- [x] Add note if abstract is unavailable 
- [x] “Contact”- change text to Creator 
- [x] Define “Updated” column with a tool tip 
- [x] Remove “Funded” column from home page
- [x] Remove links at the bottom for About/ Terms of Use/ Privacy statement (keep the blurb re UC3/CDL/UC regents) 
- [x] View all/ pagination appears to be broken  
- [x] Display role name for CRediT Contributor Role (w/ link to the credit definition) 
- [x] Add ORCID logo to contributor section

**Comment by mariapraetzellis** [comment]
Small thing, but can you swap the URL for University of California Curation Center at the bottom to point to https://uc3.cdlib.org/?

**Comment by mariapraetzellis** [comment]
I've culled feedback we got from John/Catherine and added a few additional items all relating to the layout of an individual ID landing page in this google doc: https://docs.google.com/document/d/1uBUV4NHMIaYFRJjFvgdUs9igTccOdmrmoSH1NPZcMPk/edit#

**Comment by mariapraetzellis** [comment]
A few additional comments based on the updated hub landing page:

- [ ] Can we make dates default to full month rather than the abbreviated date? 
- [ ] Remove extra space between contributor name and their role 
- [ ] Under the Funding section can we break down the values?
Status: Pending/Awarded/Declined (not sure what they are currently defined as, we should review)
Funder: Funder Registry ID
Grant URL: value (Link to the grant URL) 
- [ ] Related works- do we need to show the EZID link? I'm not sure if this adds anything and might be confusing to others
- [ ] Can we move the Plan URL up to the Project Details section of the page? 
- [ ] Rename the "Ethics" field to "Ethical issues related to data that this DMP describes" (We may end up re-phrasing this down the road, but this is the best I can think of at the moment)
- [ ] We should add "Data Management Plan" to the landing page so it is clear what the record is for. Let's discuss where to put it. Thinking it could go above the project title in a different color font.

**Comment by briri** [comment]
Update wording of Search to tell users exactly what they can search for.

**Comment by mariapraetzellis** [comment]
Feedback listed below from meeting with John on 10/27. I've also noted them inline w/ a landing page here: https://drive.google.com/file/d/1OVcQuSnj0EzrpMWHaBQtRWqHHS8NGF8e/view?usp=sharing 

- [ ] Re-title the top of the page to: ""A data management plan for this project was submitted to <fundername> with the information below.""
- [ ] Re-title Contributors to ""Contributors to this project"
- [ ] Move the project ID to the bottom of the Project Details section. Change the field to read: "For more information visit the project landing page:" 
- [ ] Re-title the Funding section to "Funding status and sources for this project" 
- [ ] Re-title the Abstract section to "Project description" 
- [ ] Re-title Anticipated Outputs to "Planned outputs"
- [ ] Re-title Published Works to "Other works associated with this research project" 
- [ ] John also asked if we can group output types together under a header. So headers could be "Datasets" and "Articles". Let's discuss 
- [ ]

**Comment by mariapraetzellis** [comment]
A few more edits for the hub:

- [ ] Links to ORCIDs, RORs, and DMP DOIs, point to an error page `
ActiveRecord::RecordNotFound in DataManagementPlansController#show
`
- [ ] Link to the Data Curation role points to a 404 (https://casrai.org/Contributor_Roles/Data_curation)

- [ ] Update the Funder link to open in a new tab

- [ ] Update the Grant URL to open in a new tab

- [ ] Update the DMP logo in the top right to include a link to the DMP when you click on the logo

- [ ] Change the "here" link to the color green so that it pops out more

- [ ] Both the logo link and the "here" link for the DMPs should open in a new tab and not prompt the user to download a PDF.
