### ISSUE TITLE
Mint DMP DOIs via DataCite 

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#3]
Develop code to translate our data model into appropriate Datacite metadata
Develop code to mint a DOI for a DMP via Datacite

**Comment by briri** [comment]
Going to close this one. The initial code this is in place. We will need to harden up our tests and ensure that all error conditions are properly handled. Will open a separate ticket for this.

We will also need to figure out a workflow for dealing with DOI mint failures. For example, do we still capture the DMP metadata and allow a DMPHub admin to correct any issues and then re-try the minting process? If so how does the origin of the DMP metadata (e.g. DMPTool) get notified of the DOI afterward.
