### ISSUE TITLE
Change ORCID reqs for DMP ID

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#48]
Right now we require at least one contributor to be listed w/ a ORCID in order for a researcher to mint an ID. We should change this so that at a minimum we need an ORCID for the DMP creator and they are not required to add additional contributors.

**Comment by mariapraetzellis** [comment]
This looks like it is working as expected now. Thanks! I'd just like to make a small change to the text regarding linking the ORCID to:
"linked your DMPTool account to your ORCID via the DMPTool profile page" Is it possible to make "DMPTool profile page" a link that goes to their profile view?

**Comment by briri** [comment]
done. thanks for testing!

<img width="573" alt="Screen Shot 2021-04-21 at 1 49 26 PM" src="https://user-images.githubusercontent.com/1204467/115619198-72410000-a2a8-11eb-9315-9425a2f3845e.png">
