### ISSUE TITLE
Build harvester to scan NSF Awards API and send assertions to EventData

### ISSUE THREAD

**Issue by mariapraetzellis** [CDLUC3/dmphub#5]
Build a separate Harvester app that scans NSF Awards API and sends assertions to EventData 

1. Develop code that grabs lists of DOIs to search NSF for from `GET /data_management_plans`
2. Develop code to hit NSF API
3. Develop code to send assertions to EventData
4. Develop code (in Hub) to hit Datacite to look for assertions made through EventData (e.g. Grant/Award URIs) for use in the `GET /data_management_plans/:id` endpoint and the landing page

**Comment by briri** [comment]
Going to close this one. The initial code this is in place. 

We have some more work to do on this front. I will open separate tickets though.
