### ISSUE TITLE
Evaluate new metadata and define how to display it on the landing pages

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmphub#57]
For example we now collect the following but do not display it anywhere on the landing pages (maybe we don't need/want to):
- Field of Science
- Metadata standards
- Some narrative elements about preservation and privacy (lifted from the DMP via theme matching)

**Comment by mariapraetzellis** [comment]
**Research domain** (Field of Science) can be displayed in the Project details section 
**Metadata standards** can be displayed in the associated Planned outputs section. 
I don't think we should include the narrative elements re preservation/privacy at this point- though we may incorporate this in the future. 

@briri

**Comment by mariapraetzellis** [comment]
Also related, the DMP ID citation is currently pointing to the wrong DOI. For example: For https://dmphub.cdlib.org/dmps/doi:10.48321/D1F88S the citation points to the wrong DOI (https://doi.org/10.1111/j.1365-294X.2007.03538.x) and it should go to https://doi.org/10.48321/D1F88S
