### ISSUE TITLE
Link back to the PDF copy of the DMP not working

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmphub#58]
Clicking the link to the original DMP results in:
```JSON
{
  "api_version": 2,
  "source": "GET /api/v2/plans/68380.pdf",
  "time": "2021-08-12T08:23:35-07:00",
  "code": 401,
  "message": "Unauthorized",
  "total_items": 0,
  "items": [

  ],
  "errors": [
    "token is invalid, expired or has been revoked"
  ]
}
```

See the following for an example: https://dmphub.cdlib.org/dmps/doi:10.48321/D1D88G

This is due to the new security restrictions added to API v2. We need to update so that we call the API using the DMPTool's API (passing `grant_type=client_credentials&client_id=123&client_secret=ABC&scope=read_dmps` to the token request)

**Comment by briri** [comment]
temporary fix put in place. Leaving this open to address properly in Sept.

**Comment by mariapraetzellis** [comment]
The current process sends you to the DMPTool PDF instead of going through the API. This link only displays if it is publicly visible.
