### ISSUE TITLE
General environment setup

### ISSUE THREAD

**Issue by briri** [CDLUC3/dmphub#74]
We need to establish/define some initial settings for the new AWS environment

- [x] Define tags we want to use (e.g. Service: 'dmp', Sub-service: 'hub')
- [x] Define resource naming conventions (e.g. is 'dmp-hub-lambda-get' redundant if we have 'dmp' and 'hub' tags)
- [x] Review inital IAM group and related policies, users, and roles (assuming we will refine down the road)
- [x] Define SSM variable naming conventions (possibly just reusing what's already out there)
- [ ] Define how we want to handle logging in CloudWatch
- [ ] Define CloudWatch alarms and metrics (or will we use Nagios)
- [ ] Determine if we want to use CloudTrail and if we will continue to use Librato

Discuss how best to handle data between environments. We currently have an RDS per environment but DynamoDB costs are different and it may make more sense to have one for prod and another shared by dev and stage.

I also have an unknown that may determine a need for additional infrastructure. We are going to use Cognito user pools and I will be storing 'provenance' with aspects of the DMP record to indicate who created/updated it. 
- Will we be able to get email addresses / orcid ids from Cognito or do we only get a Cognito UUID?
- If we use a Cognito UUID, what happens if we need to rebuild the env from CloudFormation? Is the user pool backed up and restored?

Depending on the answer to the above question about Cognito, it may make sense to build a small Postgres RDS instance that can be used to persist this.

**Comment by briri** [comment]
Interesting article on the use of SSM params in a CloudFormation template. https://medium.com/claranet-italia/a-practical-guide-to-surviving-aws-sam-d8ab141b3d25

Will need to think on how to handle this @ashleygould since the DMPHub 2.0 will not have EC2 hosts, so it may be harder to distinguish between stg in prd.

**Comment by mariapraetzellis** [comment]
@ashleygould will determine how best to handle logging.
